apiVersion: v2
name: unitycatalog
description: A Helm chart to deploy Unity Catalog on Kubernetes
home: "https://github.com/unitycatalog/unitycatalog/tree/main/helm"
sources: ["https://github.com/unitycatalog/unitycatalog/tree/main/helm"]
type: application

version: 0.1.0
appVersion: "v0.2.1"
