name: Docs Generation Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

jobs:
  docs-generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: "docs/.nvmrc"
          registry-url: https://registry.npmjs.org
      - run: npm ci
        working-directory: docs
      - run: npm run build
        working-directory: docs

  openapi-docs-validation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Generate OpenAPI API and Model docs
        run: build/sbt generate

      - name: Check Generated Docs Differences
        run: |
          DOCS_DIFF=$(git ls-files --others --modified --exclude-standard)
          if [[ -n $DOCS_DIFF ]]; then
            echo "This PR contains changes that should also update the generated docs using build/sbt generate"
            echo "If you have changed the UC REST APIs such that changes to generated docs are expected, then please make sure all generated docs have been properly updated in this PR."
            echo "Otherwise, without changes to UC REST APIs, manual changes to the generated docs are not acceptable."
            echo "Modified or untracked doc files:"
            echo "$DOCS_DIFF"
            exit 1
          else
            echo "No changes to generated docs detected."
          fi
        shell: bash
