name: Mark Issue as 'Needs Review'

on:
  issues:
    types: [opened, reopened]
  issue_comment:
    types: [created]




jobs:
  automate-updated-issues:
    if: ${{ !github.event.issue.pull_request && !contains('tdas ravivijay-db vikrantpuppala', github.event.sender.login) }}
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: PRs and Issues Board
          column: Needs Review
          repo-token: ${{ secrets.PROJECT_BOARD_AUTOMATION_TOKEN }}