name: Mark PR as 'Needs Review'

on:
  pull_request_target:
    types: [ opened, reopened, review_requested, ready_for_review, review_request_removed ]
  issue_comment:
    types: [ created ]
  pull_request_review_comment:
    types: [ created ]

jobs:
  automate-updated-prs:
    if: ${{ (github.event.issue.pull_request || github.event.pull_request) &&
      !contains('tdas ravivijay-db', github.event.sender.login) &&
      (github.event.pull_request.state == 'open' || github.event.issue.state == 'open') }}
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: PRs and Issues Board
          column: Needs Review
          repo-token: ${{ secrets.PROJECT_BOARD_AUTOMATION_TOKEN }}
